### ISSUE TITLE
Upcoming core change: removing EventManager

### ISSUE THREAD

**Issue by zerocrates** [biblibre/omeka-plugin-Export#2]
An upcoming release of the Omeka Classic core removes many obsolete, unused/underused Zend Framework components, primarily to lessen the burden of keeping them updated as upstream support has long since ended.

I notice that this plugin uses one of the components slated for removal, the backported EventManager. So I'm just reaching out to inform about the change and think over options.

Maybe the most straightforward solution would be to use Omeka Classic's native event system (hooks and filters) instead of EventManager here. I don't know if you have knowledge of many/any other plugins that are using the event this one provides; obviously that affects how complicated any change would be.

**Comment by jajm** [comment]
Thank you for the heads up.
It's always good to see the number of dependencies go down, even if it requires to rewrite some stuff.
To my knowledge there is only one plugin using that, and it's a plugin specific to one of our clients that is not going to be upgraded to 3.0 any time soon, so it should be ok :)

**Comment by jmechnich** [comment]
As announced by the original poster of this issue, this plugin does not work anymore with current versions of Omeka Classic (in my case 3.1).
Are there any plans for updating it?

**Comment by jajm** [comment]
I just released [v0.2.0](https://github.com/biblibre/omeka-plugin-Export/releases/tag/v0.2.0) which should work with Omeka Classic 3.1.
Can you confirm it works for you too ?

**Comment by jmechnich** [comment]
Sorry for the late reply: seems to be working great. Thank you for the quick resolution!

**Comment by jmechnich** [comment]
Sorry for the late reply: seems to be working great. Thank you for the quick resolution!

**Comment by jajm** [comment]
Thanks for testing!
